FROM n8nio/n8n:latest

ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV NODE_ENV=production
ENV N8N_HOST=${RAILWAY_PUBLIC_DOMAIN}
ENV WEBHOOK_URL=https://${RAILWAY_PUBLIC_DOMAIN}

EXPOSE 5678

CMD ["n8n", "start"]
